/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:59de92aa-36d7-46a7-81df-fd47c2deeafb",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_4HX7M8cay",
    "aws_user_pools_web_client_id": "12vn3170e3h2l0dldrfcui2kin",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "FileMetadataTable-dev",
            "region": "us-east-2"
        }
    ],
    "aws_user_files_s3_bucket": "docvaultfiles3a9d1-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
